version: "3"
services:
  db_recipes:
    restart: always
    image: "postgres:10.3-alpine"
    volumes:
    - /usr/src/recipes/postgresql:/var/lib/postgresql/data
    env_file:
    - ./.env.secret
    networks:
    - default

  web_recipes:
    build: .
    restart: always
    env_file:
    - ./.env.secret
    command: "gunicorn --bind 0.0.0.0:8080 recipes.wsgi"
    volumes:
    - .:/Recipes
    depends_on:
    - db_recipes
    networks:
    - default

  nginx_recipes:
    image: "nginx"
    restart: always
    env_file:
    - ./.env
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./staticfiles:/static
    - ./mediafiles:/media
    networks:
      - default
      - nginx-proxy

networks:
  default:
  nginx-proxy:
    external:
      name: nginx-proxy
